nome = str(input('Digite seu nome completo: ')).strip()
nomeA = nome.split()
print('Muito prazer em te conhecer')
print('Seu primeiro nome é {}'.format(nomeA[0]))
print('Seu último nome é {}'.format(nome[len(nome)-1]))